from django.urls import path, re_path
from django.views.generic import RedirectView

from . import views

app_name = "dashboard"

urlpatterns = [
    path("welcome/", views.welcome_view, name="welcome"),
    path("login/", views.login_view, name="login"),
    path("register-here/", views.register_options_view, name="register_options"),
    path("forgot-password/", views.forgot_password_view, name="forgot_password"),
    path("reset-password/<str:token>/", views.password_reset_confirm_view, name="password_reset_confirm"),
    path("verify-email/<str:token>/", views.verify_email_view, name="verify_email"),
    path("api/test-email-otp/", views.api_test_email_otp, name="api_test_email_otp"),
    path("company/register/", views.company_register_view, name="company_register"),
    path("consultancy/register/", views.consultancy_register_view, name="consultancy_register"),
    path("candidate/register/", views.candidate_register_view, name="candidate_register"),
    path(
        "api/candidate-registration-suggestions/",
        views.candidate_registration_suggestions_api,
        name="candidate_registration_suggestions_api",
    ),
    path("otp/send/", views.send_registration_otp, name="send_registration_otp"),
    path("otp/verify/", views.verify_registration_otp, name="verify_registration_otp"),
    path("api/panel-notifications/", views.panel_notifications_api, name="panel_notifications_api"),
    path("company/login/", views.company_login_view, name="company_login"),
    path("company/logout/", views.company_logout_view, name="company_logout"),
    path("consultancy/logout/", views.consultancy_logout_view, name="consultancy_logout"),
    path("candidate/logout/", views.candidate_logout_view, name="candidate_logout"),
    path("consultancy/dashboard/", views.consultancy_dashboard_view, name="consultancy_dashboard"),
    path("consultancy/job-management/", views.consultancy_jobs_view, name="consultancy_jobs"),
    path(
        "consultancy/job-management/api/metrics/",
        views.consultancy_jobs_metrics_api,
        name="consultancy_jobs_metrics_api",
    ),
    path("consultancy/job-management/<str:job_id>/", views.consultancy_job_detail_view, name="consultancy_job_detail"),
    path("consultancy/assigned-jobs/", views.consultancy_assigned_jobs_view, name="consultancy_assigned_jobs"),
    path("consultancy/candidate-pool/", views.consultancy_candidate_pool_view, name="consultancy_candidate_pool"),
    path("consultancy/applications/", views.consultancy_applications_view, name="consultancy_applications"),
    path(
        "consultancy/applications/<str:application_id>/resume/",
        views.consultancy_application_resume_view,
        name="consultancy_application_resume",
    ),
    path("consultancy/shortlisted/", views.consultancy_shortlisted_view, name="consultancy_shortlisted"),
    path("consultancy/interviews/", views.consultancy_interviews_view, name="consultancy_interviews"),
    path("consultancy/placements/", views.consultancy_placements_view, name="consultancy_placements"),
    path("consultancy/earnings/", views.consultancy_earnings_view, name="consultancy_earnings"),
    path("consultancy/communication/", views.consultancy_communication_view, name="consultancy_communication"),
    path("consultancy/messages/", views.consultancy_messages_view, name="consultancy_messages"),
    path("consultancy/feedback/", views.consultancy_feedback_view, name="consultancy_feedback"),
    path("consultancy/reports/", views.consultancy_reports_view, name="consultancy_reports"),
    path("consultancy/profile-settings/", views.consultancy_profile_settings_view, name="consultancy_profile_settings"),
    path(
        "consultancy/subscription/",
        views.consultancy_subscription_view,
        name="consultancy_subscription",
    ),
    path(
        "consultancy/support/",
        views.consultancy_support_view,
        {"section": "create"},
        name="consultancy_support",
    ),
    path(
        "consultancy/support/create/",
        views.consultancy_support_view,
        {"section": "create"},
        name="consultancy_support_create",
    ),
    path(
        "consultancy/support/my-tickets/",
        views.consultancy_support_view,
        {"section": "my-tickets"},
        name="consultancy_support_tickets",
    ),
    path(
        "consultancy/support/open/",
        views.consultancy_support_view,
        {"section": "open"},
        name="consultancy_support_open",
    ),
    path(
        "consultancy/support/closed/",
        views.consultancy_support_view,
        {"section": "closed"},
        name="consultancy_support_closed",
    ),
    path(
        "consultancy/support/knowledge-base/",
        views.consultancy_support_view,
        {"section": "knowledge"},
        name="consultancy_support_knowledge",
    ),
    path(
        "consultancy/support/live-chat/",
        views.consultancy_support_view,
        {"section": "chat"},
        name="consultancy_support_chat",
    ),
    path(
        "consultancy/support/ticket/<str:ticket_id>/",
        views.consultancy_support_view,
        {"section": "details"},
        name="consultancy_support_detail",
    ),
    path("candidate/dashboard/", views.candidate_dashboard_view, name="candidate_dashboard"),
    path("candidate/profile/", views.candidate_profile_view, name="candidate_profile"),
    path("candidate/resume-manager/", views.candidate_resume_manager_view, name="candidate_resume_manager"),
    path("candidate/job-search/", views.candidate_job_search_view, name="candidate_job_search"),
    path(
        "candidate/api/job-search-suggestions/",
        views.candidate_job_search_suggestions_api,
        name="candidate_job_search_suggestions_api",
    ),
    path("candidate/job-search/<str:job_id>/", views.candidate_job_detail_view, name="candidate_job_detail"),
    path("candidate/saved-jobs/", views.candidate_saved_jobs_view, name="candidate_saved_jobs"),
    path("candidate/applications/", views.candidate_applications_view, name="candidate_applications"),
    path("candidate/interviews/", views.candidate_interviews_view, name="candidate_interviews"),
    path("candidate/messages/", views.candidate_messages_view, name="candidate_messages"),
    path("candidate/notifications/", views.candidate_notifications_view, name="candidate_notifications"),
    path("candidate/subscription/", views.candidate_subscription_view, name="candidate_subscription"),
    path("candidate/settings/", views.candidate_settings_view, name="candidate_settings"),
    path("candidate/support/", views.candidate_support_view, name="candidate_support"),
    path("candidate/feedback/", views.candidate_feedback_view, name="candidate_feedback"),
    path("company/dashboard/", views.company_dashboard_view, name="company_dashboard"),
    path("company/api/metrics/", views.api_company_metrics, name="company_api_metrics"),
    path("company/api/feedbacks/", views.api_company_feedbacks, name="company_feedbacks_api"),
    path(
        "company/api/applications/<str:application_id>/thread/",
        views.api_company_application_thread,
        name="company_api_application_thread",
    ),
    path(
        "company/api/security/activity/",
        views.api_company_security_activity,
        name="company_api_security_activity",
    ),
    path("consultancy/api/metrics/", views.api_consultancy_metrics, name="consultancy_api_metrics"),
    path("consultancy/api/feedbacks/", views.api_consultancy_feedbacks, name="consultancy_feedbacks_api"),
    path("company/profile/", views.company_profile_view, name="company_profile"),
    path("company/jobs/", views.company_jobs_view, name="company_jobs"),
    path("company/feedback/", views.company_feedback_view, name="company_feedback"),
    path("company/applications/", views.company_applications_view, name="company_applications"),
    path("company/messages/", views.company_messages_view, name="company_messages"),
    path(
        "company/applications/<str:application_id>/resume/",
        views.company_application_resume_view,
        name="company_application_resume",
    ),
    path(
        "company/communication/",
        views.company_communication_view,
        {"section": "bulk-email"},
        name="company_communication",
    ),
    path(
        "company/communication/bulk-email/",
        views.company_communication_view,
        {"section": "bulk-email"},
        name="company_communication_bulk_email",
    ),
    path(
        "company/communication/bulk-sms/",
        views.company_communication_view,
        {"section": "bulk-sms"},
        name="company_communication_bulk_sms",
    ),
    path(
        "company/communication/whatsapp/",
        views.company_communication_view,
        {"section": "whatsapp"},
        name="company_communication_whatsapp",
    ),
    path(
        "company/communication/notifications/",
        views.company_communication_view,
        {"section": "notifications"},
        name="company_communication_notifications",
    ),
    path(
        "company/communication/templates/",
        views.company_communication_view,
        {"section": "templates"},
        name="company_communication_templates",
    ),
    path(
        "company/communication/sent-history/",
        views.company_communication_view,
        {"section": "sent-history"},
        name="company_communication_sent_history",
    ),
    path(
        "company/communication/scheduled/",
        views.company_communication_view,
        {"section": "scheduled"},
        name="company_communication_scheduled",
    ),
    path(
        "company/interviews/",
        views.company_interviews_view,
        {"section": "schedule"},
        name="company_interviews",
    ),
    path(
        "company/interviews/schedule/",
        views.company_interviews_view,
        {"section": "schedule"},
        name="company_interviews_schedule",
    ),
    path(
        "company/interviews/upcoming/",
        views.company_interviews_view,
        {"section": "upcoming"},
        name="company_interviews_upcoming",
    ),
    path(
        "company/interviews/completed/",
        views.company_interviews_view,
        {"section": "completed"},
        name="company_interviews_completed",
    ),
    path(
        "company/interviews/cancelled/",
        views.company_interviews_view,
        {"section": "cancelled"},
        name="company_interviews_cancelled",
    ),
    path(
        "company/interviews/feedback/",
        views.company_interviews_view,
        {"section": "feedback"},
        name="company_interviews_feedback",
    ),
    path("company/reports/", views.company_reports_view, name="company_reports"),
    path("company/billing/", views.company_billing_view, name="company_billing"),
    path("company/grievance/", views.company_grievance_view, name="company_grievance"),
    path("company/settings/", views.company_settings_view, name="company_settings"),
    path("company/security/", views.company_security_view, name="company_security"),
    path(
        "company/support/",
        views.company_support_view,
        {"section": "create"},
        name="company_support",
    ),
    path(
        "company/support/create/",
        views.company_support_view,
        {"section": "create"},
        name="company_support_create",
    ),
    path(
        "company/support/my-tickets/",
        views.company_support_view,
        {"section": "my-tickets"},
        name="company_support_tickets",
    ),
    path(
        "company/support/open/",
        views.company_support_view,
        {"section": "open"},
        name="company_support_open",
    ),
    path(
        "company/support/closed/",
        views.company_support_view,
        {"section": "closed"},
        name="company_support_closed",
    ),
    path(
        "company/support/knowledge-base/",
        views.company_support_view,
        {"section": "knowledge"},
        name="company_support_knowledge",
    ),
    path(
        "company/support/live-chat/",
        views.company_support_view,
        {"section": "chat"},
        name="company_support_chat",
    ),
    path(
        "company/support/ticket/<str:ticket_id>/",
        views.company_support_view,
        {"section": "details"},
        name="company_support_detail",
    ),
    path("logout/", views.logout_view, name="logout"),
    path("admin-dashboard/", views.dashboard_view, name="dashboard"),
    path("subadmin-dashboard/", views.subadmin_dashboard_view, name="subadmin_dashboard"),
    path(
        "admin-dashboard/profile/",
        views.admin_profile_view,
        {"section": "all"},
        name="admin_profile",
    ),
    path(
        "admin-dashboard/profile/last-login/",
        views.admin_profile_view,
        {"section": "last-login"},
        name="admin_profile_last_login",
    ),
    path(
        "admin-dashboard/profile/photo/",
        views.admin_profile_view,
        {"section": "photo"},
        name="admin_profile_photo",
    ),
    path(
        "admin-dashboard/profile/password/",
        views.admin_profile_view,
        {"section": "password"},
        name="admin_profile_password",
    ),
    path("companies/", views.companies_view, name="companies"),
    path("consultancies/", views.consultancies_view, name="consultancies"),
    path("candidates/", views.candidates_view, name="candidates"),
    path("jobs/", views.jobs_view, name="jobs"),
    path("jobs/pending/", views.jobs_pending_view, name="jobs_pending"),
    path("jobs/approved/", views.jobs_approved_view, name="jobs_approved"),
    path("jobs/rejected/", views.jobs_rejected_view, name="jobs_rejected"),
    path("jobs/reported/", views.jobs_reported_view, name="jobs_reported"),
    path("applications/", views.applications_view, name="applications"),
    path("applications/interview/", views.applications_interview_view, name="applications_interview"),
    path("applications/selected/", views.applications_selected_view, name="applications_selected"),
    path("applications/rejected/", views.applications_rejected_view, name="applications_rejected"),
    path("applications/offer/", views.applications_offer_view, name="applications_offer"),
    path("feedbacks/", views.admin_feedbacks_view, name="admin_feedbacks"),
    path("subscriptions/", views.subscriptions_view, name="subscriptions"),
    path(
        "subscriptions/free-paid/",
        views.subscriptions_free_paid_view,
        name="subscriptions_free_paid",
    ),
    path(
        "subscriptions/expiry-alerts/",
        views.subscriptions_expiry_alerts_view,
        name="subscriptions_expiry_alerts",
    ),
    path(
        "subscriptions/revenue/",
        views.subscriptions_revenue_view,
        name="subscriptions_revenue",
    ),
    path(
        "subscriptions/manual-assign/",
        views.subscriptions_manual_assign_view,
        name="subscriptions_manual_assign",
    ),
    path(
        "advertisement-management/",
        views.advertisement_management_view,
        name="advertisement_management",
    ),
    path(
        "communication-center/",
        views.communication_center_view,
        name="communication_center",
    ),
    path(
        "communication-center/bulk-email/",
        views.communication_bulk_email_view,
        name="communication_bulk_email",
    ),
    path(
        "communication-center/bulk-sms/",
        views.communication_bulk_sms_view,
        name="communication_bulk_sms",
    ),
    path(
        "communication-center/notifications/",
        views.communication_notifications_view,
        name="communication_notifications",
    ),
    path(
        "communication-center/whatsapp-alerts/",
        views.communication_whatsapp_view,
        name="communication_whatsapp",
    ),
    path("message-monitor/", views.message_monitor_view, name="message_monitor"),
    path(
        "communication-center/message-templates/",
        views.communication_templates_view,
        name="communication_templates",
    ),
    path(
        "communication-center/sent-history/",
        views.communication_sent_history_view,
        name="communication_sent_history",
    ),
    path(
        "communication-center/scheduled-messages/",
        views.communication_scheduled_view,
        name="communication_scheduled",
    ),
    path(
        "support-center/",
        views.support_center_view,
        {"section": "dashboard"},
        name="support_center",
    ),
    path(
        "support-center/tickets/",
        views.support_center_view,
        {"section": "all"},
        name="support_tickets",
    ),
    path(
        "support-center/high-priority/",
        views.support_center_view,
        {"section": "high"},
        name="support_high_priority",
    ),
    path(
        "support-center/assigned/",
        views.support_center_view,
        {"section": "assigned"},
        name="support_assigned",
    ),
    path(
        "support-center/unassigned/",
        views.support_center_view,
        {"section": "unassigned"},
        name="support_unassigned",
    ),
    path(
        "support-center/closed/",
        views.support_center_view,
        {"section": "closed"},
        name="support_closed",
    ),
    path(
        "support-center/analytics/",
        views.support_center_view,
        {"section": "analytics"},
        name="support_analytics",
    ),
    path("grievance/", views.grievance_reports_view, name="grievance_reports"),
    path(
        "grievance/user-complaints/",
        views.grievance_complaints_view,
        name="grievance_complaints",
    ),
    path(
        "grievance/job-reports/",
        views.grievance_job_reports_view,
        name="grievance_job_reports",
    ),
    path(
        "grievance/abuse-fraud/",
        views.grievance_abuse_fraud_view,
        name="grievance_abuse_fraud",
    ),
    path(
        "grievance/resolution-log/",
        views.grievance_resolution_log_view,
        name="grievance_resolution_log",
    ),
    path(
        "security/login-history/",
        views.security_login_history_view,
        name="security_login_history",
    ),
    path(
        "security/ip-logs/",
        views.security_ip_logs_view,
        name="security_ip_logs",
    ),
    path(
        "security/admin-activity/",
        views.security_admin_activity_view,
        name="security_admin_activity",
    ),
    path(
        "security/role-permissions/",
        views.security_role_permissions_view,
        name="security_role_permissions",
    ),
    path(
        "api/security/login-history/",
        views.api_security_login_history,
        name="api_security_login_history",
    ),
    path(
        "api/messages/thread/<int:thread_id>/",
        views.api_thread_messages,
        name="api_thread_messages",
    ),
    path(
        "api/messages/thread/<int:thread_id>/send/",
        views.api_thread_send_message,
        name="api_thread_send_message",
    ),
    path("api/subadmins/list/", views.api_subadmin_list, name="api_subadmin_list"),
    path("api/subadmins/create/", views.api_subadmin_create, name="api_subadmin_create"),
    path(
        "api/subadmins/<int:pk>/detail/",
        views.api_subadmin_detail,
        name="api_subadmin_detail",
    ),
    path(
        "api/subadmins/<int:pk>/update/",
        views.api_subadmin_update,
        name="api_subadmin_update",
    ),
    path(
        "api/subadmins/<int:pk>/delete/",
        views.api_subadmin_delete,
        name="api_subadmin_delete",
    ),
    path("settings/", views.settings_platform_view, name="settings_platform"),
    path(
        "settings/job-categories/",
        views.settings_job_categories_view,
        name="settings_job_categories",
    ),
    path("settings/locations/", views.settings_locations_view, name="settings_locations"),
    path("settings/skills/", views.settings_skills_view, name="settings_skills"),
    path(
        "settings/experience-levels/",
        views.settings_experience_levels_view,
        name="settings_experience_levels",
    ),
    path("api/user-management/<str:user_type>/list/", views.api_user_list, name="api_user_list"),
    path("api/user-management/<str:user_type>/create/", views.api_user_create, name="api_user_create"),
    path(
        "api/user-management/<str:user_type>/<int:pk>/update/",
        views.api_user_update,
        name="api_user_update",
    ),
    path(
        "api/user-management/<str:user_type>/<int:pk>/delete/",
        views.api_user_delete,
        name="api_user_delete",
    ),
    path(
        "api/user-management/<str:user_type>/<int:pk>/detail/",
        views.api_user_detail,
        name="api_user_detail",
    ),
    path(
        "api/user-management/<str:user_type>/<int:pk>/status/",
        views.api_user_status,
        name="api_user_status",
    ),
    path(
        "api/user-management/<str:user_type>/<int:pk>/kyc/",
        views.api_user_kyc,
        name="api_user_kyc",
    ),
    path(
        "api/user-management/<str:user_type>/bulk-delete/",
        views.api_user_bulk_delete,
        name="api_user_bulk_delete",
    ),
    path("api/user-management/<str:user_type>/export/", views.api_user_export, name="api_user_export"),
    path("api/plans/list/", views.api_plans_list, name="api_plans_list"),
    path("api/plans/create/", views.api_plans_create, name="api_plans_create"),
    path("api/plans/<int:plan_id>/update/", views.api_plans_update, name="api_plans_update"),
    path("api/plans/<int:plan_id>/delete/", views.api_plans_delete, name="api_plans_delete"),
    path("api/jobs/list/", views.api_jobs_list, name="api_jobs_list"),
    path("api/jobs/create/", views.api_jobs_create, name="api_jobs_create"),
    path("api/jobs/<str:job_id>/update/", views.api_jobs_update, name="api_jobs_update"),
    path("api/jobs/<str:job_id>/delete/", views.api_jobs_delete, name="api_jobs_delete"),
    path("api/jobs/export/", views.api_jobs_export, name="api_jobs_export"),
    path("api/applications/list/", views.api_applications_list, name="api_applications_list"),
    path("api/applications/create/", views.api_applications_create, name="api_applications_create"),
    path(
        "api/applications/<str:application_id>/update/",
        views.api_applications_update,
        name="api_applications_update",
    ),
    path(
        "api/applications/<str:application_id>/delete/",
        views.api_applications_delete,
        name="api_applications_delete",
    ),
    path("api/applications/export/", views.api_applications_export, name="api_applications_export"),
    path("api/subscriptions/list/", views.api_subscriptions_list, name="api_subscriptions_list"),
    path("api/subscriptions/create/", views.api_subscriptions_create, name="api_subscriptions_create"),
    path(
        "api/subscriptions/<str:subscription_id>/update/",
        views.api_subscriptions_update,
        name="api_subscriptions_update",
    ),
    path(
        "api/subscriptions/<str:subscription_id>/extend/",
        views.api_subscriptions_extend,
        name="api_subscriptions_extend",
    ),
    path(
        "api/subscriptions/<str:subscription_id>/delete/",
        views.api_subscriptions_delete,
        name="api_subscriptions_delete",
    ),
    path(
        "api/subscriptions/<str:subscription_id>/payments/",
        views.api_subscription_payments,
        name="api_subscription_payments",
    ),
    path("api/payment/initiate/", views.api_payment_initiate, name="api_payment_initiate"),
    path("api/payment/initiate", views.api_payment_initiate, name="api_payment_initiate_noslash"),
    path("api/payment/callback/", views.api_payment_callback, name="api_payment_callback"),
    path("api/payment/callback", views.api_payment_callback, name="api_payment_callback_noslash"),
    path(
        "payment-system/checkout/<str:payment_id>/",
        views.payment_system_checkout_view,
        name="payment_system_checkout",
    ),
    path(
        "payment-system/checkout/<str:payment_id>",
        views.payment_system_checkout_view,
        name="payment_system_checkout_noslash",
    ),
    path(
        "payment-system/process/<str:payment_id>/",
        views.payment_system_process_view,
        name="payment_system_process",
    ),
    path(
        "payment-system/process/<str:payment_id>",
        views.payment_system_process_view,
        name="payment_system_process_noslash",
    ),
    path(
        "api/payment/status/<str:payment_id>/",
        views.api_payment_status,
        name="api_payment_status",
    ),
    path(
        "api/payment/status/<str:payment_id>",
        views.api_payment_status,
        name="api_payment_status_noslash",
    ),
    path("payment/redirect/", views.payment_redirect_view, name="payment_redirect"),
    path("payment/redirect", views.payment_redirect_view, name="payment_redirect_noslash"),
    path("payment/redirect/login/", views.payment_redirect_view, name="payment_redirect_login_legacy"),
    path("payment/redirect/login", views.payment_redirect_view, name="payment_redirect_login_legacy_noslash"),
    re_path(
        r"^payment/re(?:/.*)?$",
        RedirectView.as_view(pattern_name="dashboard:login", permanent=False),
        name="payment_re_legacy",
    ),
    re_path(
        r"^(?:127\.0\.0\.1(?::\d+)?|localhost(?::\d+)?)/payment/re(?:/.*)?$",
        RedirectView.as_view(pattern_name="dashboard:login", permanent=False),
        name="payment_re_hostprefixed_legacy",
    ),
    re_path(
        r"^(?:127\.0\.0\.1(?::\d+)?|localhost(?::\d+)?)/payment/redirect/login/?$",
        views.payment_redirect_view,
        name="payment_redirect_hostprefixed_legacy",
    ),
    path("api/dashboard/metrics/", views.api_dashboard_metrics, name="api_dashboard_metrics"),
    path("candidate/api/applications/", views.api_candidate_applications, name="candidate_api_applications"),
    path("candidate/api/metrics/", views.api_candidate_metrics, name="candidate_api_metrics"),
    path("candidate/api/feedbacks/", views.api_candidate_feedbacks, name="candidate_feedbacks_api"),
    path(
        "candidate/api/saved-jobs/toggle/",
        views.api_candidate_toggle_saved_job,
        name="candidate_api_toggle_saved_job",
    ),
    path("api/feedbacks/admin/", views.api_admin_feedbacks, name="admin_feedbacks_api"),
    path("api/public/jobs/", views.api_public_jobs_list, name="api_public_jobs_list"),
    path("api/public/metrics/", views.api_public_metrics, name="api_public_metrics"),
    path("api/public/metrics", views.api_public_metrics, name="api_public_metrics_noslash"),
    path("api/public/feedbacks/", views.api_public_feedbacks, name="api_public_feedbacks"),
    path("api/public/feedbacks", views.api_public_feedbacks, name="api_public_feedbacks_noslash"),
]
