# Generated by Django 4.2.7 on 2026-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('profile_completion', models.PositiveIntegerField(default=0)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='documents/candidates/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='documents/candidates/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('profile_completion', models.PositiveIntegerField(default=0)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=120)),
                ('cin_number', models.CharField(blank=True, max_length=120)),
                ('registration_document', models.FileField(blank=True, null=True, upload_to='documents/companies/')),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('plan_type', models.CharField(blank=True, choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], max_length=20)),
                ('plan_start', models.DateField(blank=True, null=True)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Due', 'Due'), ('Failed', 'Failed')], max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('profile_completion', models.PositiveIntegerField(default=0)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Blocked', 'Blocked')], default='Active', max_length=20)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('suspension_reason', models.CharField(blank=True, max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=120)),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='documents/consultancies/')),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('plan_type', models.CharField(blank=True, choices=[('Free', 'Free'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], max_length=20)),
                ('plan_start', models.DateField(blank=True, null=True)),
                ('plan_expiry', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Due', 'Due'), ('Failed', 'Failed')], max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
