# Generated by Django 4.2.7 on 2026-02-16 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=120)),
                ("job_type", models.CharField(choices=[("Full-time", "Full-time"), ("Part-time", "Part-time"), ("Contract", "Contract"), ("Remote", "Remote")], default="Full-time", max_length=20)),
                ("salary", models.CharField(blank=True, max_length=120)),
                ("experience", models.CharField(blank=True, max_length=120)),
                ("skills", models.CharField(blank=True, max_length=255)),
                ("posted_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("Pending", "Pending"), ("Approved", "Approved"), ("Rejected", "Rejected"), ("Reported", "Reported")], default="Pending", max_length=20)),
                ("applicants", models.PositiveIntegerField(default=0)),
                ("verification", models.CharField(choices=[("Verified", "Verified"), ("Pending", "Pending"), ("Flagged", "Flagged")], default="Pending", max_length=20)),
                ("featured", models.BooleanField(default=False)),
                ("recruiter_name", models.CharField(blank=True, max_length=200)),
                ("recruiter_email", models.EmailField(blank=True, max_length=254)),
                ("recruiter_phone", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscription_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("account_type", models.CharField(max_length=50)),
                ("plan", models.CharField(choices=[("Free", "Free"), ("Basic", "Basic"), ("Standard", "Standard"), ("Gold", "Gold")], default="Free", max_length=20)),
                ("payment_status", models.CharField(choices=[("Free", "Free"), ("Paid", "Paid"), ("Due", "Due"), ("Failed", "Failed")], default="Free", max_length=20)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("contact", models.EmailField(blank=True, max_length=254)),
                ("monthly_revenue", models.PositiveIntegerField(default=0)),
                ("auto_renew", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("application_id", models.CharField(max_length=20, unique=True)),
                ("candidate_name", models.CharField(max_length=200)),
                ("candidate_email", models.EmailField(max_length=254)),
                ("candidate_phone", models.CharField(blank=True, max_length=50)),
                ("candidate_location", models.CharField(blank=True, max_length=120)),
                ("education", models.CharField(blank=True, max_length=200)),
                ("experience", models.CharField(blank=True, max_length=120)),
                ("job_title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("status", models.CharField(choices=[("Interview Scheduled", "Interview Scheduled"), ("Selected", "Selected"), ("Rejected", "Rejected"), ("Offer Issued", "Offer Issued")], default="Interview Scheduled", max_length=30)),
                ("applied_date", models.DateField(blank=True, null=True)),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("interview_time", models.CharField(blank=True, max_length=20)),
                ("interviewer", models.CharField(blank=True, max_length=200)),
                ("offer_package", models.CharField(blank=True, max_length=120)),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_plan", models.CharField(blank=True, max_length=20)),
                ("new_plan", models.CharField(max_length=20)),
                ("admin_name", models.CharField(default="Admin", max_length=120)),
                ("action_date", models.DateField(auto_now_add=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="dashboard.subscription")),
            ],
        ),
    ]
