# Generated by Django 4.2.7 on 2026-02-18 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_application_cover_letter_application_current_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=10)),
                ('meeting_link', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('interviewer', models.CharField(blank=True, max_length=200)),
                ('panel_interviewers', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('feedback_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('technical_skills', models.TextField(blank=True)),
                ('communication_skills', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weakness', models.TextField(blank=True)),
                ('final_decision', models.CharField(blank=True, choices=[('next_round', 'Move to Next Round'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('hold', 'Hold')], max_length=20)),
                ('feedback_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='dashboard.application')),
            ],
        ),
    ]
