# Generated by Django 4.2.7 on 2026-02-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_candidate_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recent_salary',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
