# Generated by Django 4.2.7 on 2026-02-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_application_recent_salary_candidate_expected_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('company', 'Company'), ('consultancy', 'Consultancy'), ('candidate', 'Candidate')], max_length=20)),
                ('segment', models.CharField(blank=True, choices=[('subscribed', 'Subscribed'), ('non_subscribed', 'Non-Subscribed')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('posted_by', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='contact_position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='contact_position',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
