# Generated by Django 4.2.7 on 2026-02-23 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_advertisement_company_contact_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='consultancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='dashboard.consultancy'),
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='dashboard.job'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='source_consultancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_pool', to='dashboard.consultancy'),
        ),
        migrations.CreateModel(
            name='AssignedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('positions', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Urgent', 'Urgent'), ('Paused', 'Paused')], default='Active', max_length=20)),
                ('commission_type', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage'), ('Milestone', 'Milestone')], default='Fixed', max_length=20)),
                ('commission_value', models.CharField(blank=True, default='20000', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.consultancy')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.job')),
            ],
            options={
                'unique_together': {('job', 'consultancy')},
            },
        ),
    ]
