# Generated by Django 4.2.7 on 2026-02-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_application_consultancy_application_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='placement_status',
            field=models.CharField(blank=True, choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending Approval', max_length=30),
        ),
        migrations.AddField(
            model_name='interview',
            name='round',
            field=models.CharField(blank=True, choices=[('HR', 'HR'), ('Technical', 'Technical'), ('Final', 'Final')], max_length=20),
        ),
    ]
