# Generated by Django 4.2.7 on 2026-02-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_messagethread_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyKycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(blank=True, max_length=120)),
                ('document_type', models.CharField(blank=True, choices=[('license', 'License'), ('gst', 'GST Certificate'), ('incorporation', 'Certificate of Incorporation'), ('address', 'Address Proof'), ('other', 'Other')], max_length=40)),
                ('document_file', models.FileField(upload_to='documents/consultancies/kyc/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consultancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='dashboard.consultancy')),
            ],
        ),
    ]
