# Generated by Django 4.2.7 on 2026-02-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_adminprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('plan_code', models.CharField(max_length=20, unique=True)),
                ('price_monthly', models.PositiveIntegerField(default=0)),
                ('price_quarterly', models.PositiveIntegerField(default=0)),
                ('job_posts', models.CharField(blank=True, max_length=60)),
                ('job_validity', models.CharField(blank=True, max_length=60)),
                ('resume_view', models.CharField(blank=True, max_length=60)),
                ('resume_download', models.CharField(blank=True, max_length=60)),
                ('candidate_chat', models.CharField(blank=True, max_length=60)),
                ('interview_scheduler', models.CharField(blank=True, max_length=60)),
                ('auto_match', models.CharField(blank=True, max_length=60)),
                ('shortlisting', models.CharField(blank=True, max_length=60)),
                ('candidate_ranking', models.CharField(blank=True, max_length=60)),
                ('candidate_pool_manager', models.CharField(blank=True, max_length=60)),
                ('featured_jobs', models.CharField(blank=True, max_length=60)),
                ('company_branding', models.CharField(blank=True, max_length=60)),
                ('analytics_dashboard', models.CharField(blank=True, max_length=60)),
                ('support', models.CharField(blank=True, max_length=80)),
                ('dedicated_account_manager', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
