# Generated by Django 4.2.7 on 2026-02-24

from django.db import migrations


def seed_plans(apps, schema_editor):
    plan_model = apps.get_model("dashboard", "SubscriptionPlan")
    if plan_model.objects.exists():
        return

    plan_model.objects.bulk_create(
        [
            plan_model(
                name="Free Plan",
                plan_code="Free",
                price_monthly=0,
                price_quarterly=0,
                job_posts="3 free jobs (lifetime)",
                job_validity="15 days",
                resume_view="View only",
                resume_download="Not available",
                candidate_chat="Not available",
                interview_scheduler="Not available",
                auto_match="Not available",
                shortlisting="Not available",
                candidate_ranking="Not available",
                candidate_pool_manager="Not available",
                featured_jobs="Not available",
                company_branding="Job Exhibition branding",
                analytics_dashboard="Not available",
                support="Email only",
                dedicated_account_manager="Not available",
            ),
            plan_model(
                name="Basic Plan",
                plan_code="Basic",
                price_monthly=999,
                price_quarterly=2499,
                job_posts="10 / month",
                job_validity="30 days",
                resume_view="Yes",
                resume_download="Not available",
                candidate_chat="Limited",
                interview_scheduler="Not available",
                auto_match="Not available",
                shortlisting="Manual",
                candidate_ranking="Not available",
                candidate_pool_manager="Not available",
                featured_jobs="Not available",
                company_branding="Standard",
                analytics_dashboard="Basic",
                support="Email",
                dedicated_account_manager="Not available",
            ),
            plan_model(
                name="Standard Plan",
                plan_code="Standard",
                price_monthly=2499,
                price_quarterly=6999,
                job_posts="30 / month",
                job_validity="45 days",
                resume_view="Yes",
                resume_download="Limited (100)",
                candidate_chat="Yes",
                interview_scheduler="Yes",
                auto_match="Yes",
                shortlisting="Yes",
                candidate_ranking="Yes",
                candidate_pool_manager="Yes",
                featured_jobs="3 / month",
                company_branding="Standard",
                analytics_dashboard="Advanced",
                support="Priority email",
                dedicated_account_manager="No",
            ),
            plan_model(
                name="Premium / Gold",
                plan_code="Gold",
                price_monthly=4999,
                price_quarterly=12999,
                job_posts="Unlimited",
                job_validity="60 days",
                resume_view="Unlimited",
                resume_download="Unlimited",
                candidate_chat="Unlimited",
                interview_scheduler="Advanced",
                auto_match="AI-based",
                shortlisting="Yes",
                candidate_ranking="Yes",
                candidate_pool_manager="Yes",
                featured_jobs="Unlimited",
                company_branding="Highlighted",
                analytics_dashboard="Advanced",
                support="WhatsApp + Email",
                dedicated_account_manager="Yes",
            ),
        ]
    )


def unseed_plans(apps, schema_editor):
    plan_model = apps.get_model("dashboard", "SubscriptionPlan")
    plan_model.objects.filter(plan_code__in=["Free", "Basic", "Standard", "Gold"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_subscriptionplan"),
    ]

    operations = [
        migrations.RunPython(seed_plans, reverse_code=unseed_plans),
    ]
