# Generated by Django 4.2.7 on 2026-02-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_candidate_alt_phone_candidate_current_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='address_line1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='address_line2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='address_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/consultancies/'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='areas_of_operation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='company_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='consultancy_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/consultancies/'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='gst_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='industries_served',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='office_landline',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='owner_aadhaar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='owner_designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='owner_pan',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/consultancies/'),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='service_charges',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
