# Generated by Django 4.2.7 on 2026-02-24 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_consultancy_address_line1_consultancy_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='career_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='current_job_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='marital_status',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='notice_period',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_industry',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='preferred_job_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='total_experience',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='candidate',
            name='willing_to_relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidatecertification',
            name='issuing_org',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidatecertification',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='candidateresume',
            name='template_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='candidatecertification',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/candidates/certifications/'),
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_entries', to='dashboard.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('technology', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_entries', to='dashboard.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('responsibilities', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_entries', to='dashboard.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=120)),
                ('course_name', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('passing_year', models.CharField(blank=True, max_length=10)),
                ('score', models.CharField(blank=True, max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_entries', to='dashboard.candidate')),
            ],
        ),
    ]
