# Generated by Django 4.2.7 on 2026-02-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_candidate_career_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/'),
        ),
    ]
