# Generated by Django 4.2.7 on 2026-02-25 07:27

from django.db import migrations, models


def mark_existing_companies_verified(apps, schema_editor):
    Company = apps.get_model('dashboard', 'Company')
    Company.objects.all().update(email_verified=True, phone_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_advertisement_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120, unique=True)),
                ('account_type', models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company')], max_length=20)),
                ('account_id', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('consultancy', 'Consultancy'), ('candidate', 'Candidate'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('account_id', models.PositiveIntegerField(blank=True, null=True)),
                ('username_or_email', models.CharField(blank=True, max_length=254)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_success', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='employment_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='candidate',
            name='secondary_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='hr_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='company',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_companies_verified, migrations.RunPython.noop),
    ]
