# Generated by Django 4.2.7 on 2026-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_emailverificationtoken_loginhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120, unique=True)),
                ('account_type', models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('consultancy', 'Consultancy'), ('candidate', 'Candidate')], max_length=20)),
                ('account_id', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
