# Generated by Django 4.2.7 on 2026-02-28 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyKycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('document_type', models.CharField(blank=True, choices=[('gst_certificate', 'GST Certificate'), ('cin_certificate', 'CIN Certificate'), ('incorporation', 'Certificate of Incorporation'), ('address_proof', 'Address Proof'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(upload_to='documents/companies/kyc/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='dashboard.company')),
            ],
        ),
    ]
