# Generated by Django 4.2.7 on 2026-03-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_companykycdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='lifecycle_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Paused', 'Paused'), ('Closed', 'Closed'), ('Expired', 'Expired'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
    ]
