# Generated by Django 4.2.7 on 2026-03-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_job_lifecycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='commission_fixed_fee',
            field=models.PositiveIntegerField(default=25000),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='commission_milestone_notes',
            field=models.CharField(blank=True, default='Stage-wise commission release', max_length=255),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='commission_percentage',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
