# Generated by Django 4.2.7 on 2026-03-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_consultancy_commission_fixed_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='dashboard.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_candidates', to='dashboard.job')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
