# Generated by Django 4.2.7 on 2026-03-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_candidatesavedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
