# Generated by Django 4.2.7 on 2026-03-15 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_company_address_line1_company_address_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('company', 'Company'), ('consultancy', 'Consultancy')], max_length=20)),
                ('source', models.CharField(choices=[('application', 'Application'), ('job', 'Job Post'), ('general', 'General')], default='general', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('context_label', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='dashboard.application')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='dashboard.candidate')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='dashboard.company')),
                ('consultancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='dashboard.consultancy')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='dashboard.job')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
