# Generated by Django 4.2.7 on 2026-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
