# Generated by Django 4.2.7 on 2026-04-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='redirect_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
