# Generated by Django 4.2.7 on 2026-04-03 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_subscriptionpayment_redirect_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('gateway_status', models.CharField(blank=True, max_length=20)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='dashboard.subscriptionpayment')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
