# Generated by Django 4.2.7 on 2026-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_paymenteventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('company', 'Company'), ('consultancy', 'Consultancy'), ('candidate', 'Candidate')], db_index=True, max_length=20)),
                ('entity_type', models.CharField(choices=[('company_profile', 'Company Profile'), ('consultancy_profile', 'Consultancy Profile'), ('candidate_profile', 'Candidate Profile'), ('job', 'Job')], db_index=True, max_length=40)),
                ('source_model', models.CharField(blank=True, max_length=80)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('deleted_by', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='pending_registration_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='consultancy',
            name='pending_registration_password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
