# Generated by Django 4.2.7 on 2026-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_interview_candidate_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredMediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('content', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
