"""
Django settings for jobexhibition project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    """Load BASE_DIR/.env into os.environ without overriding existing variables."""
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    try:
        content = env_path.read_text(encoding="utf-8")
    except OSError:
        return

    for raw_line in content.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        if not key or key in os.environ:
            continue
        value = value.strip()
        if len(value) >= 2 and (
            (value[0] == '"' and value[-1] == '"')
            or (value[0] == "'" and value[-1] == "'")
        ):
            value = value[1:-1].strip()
        os.environ[key] = value


_load_env_file()


def _strip_problematic_cgi_env_vars():
    """
    Avoid clashing with WSGI CGI keys.

    If REDIRECT_URL/SCRIPT_URL contain absolute URLs from .env, Django can
    treat them as SCRIPT_NAME and generate malformed redirects.
    """
    for key in ("REDIRECT_URL", "SCRIPT_URL"):
        value = (os.environ.get(key) or "").strip()
        if not value:
            continue
        lowered = value.lower()
        if lowered.startswith(("http://", "https://", "http:/", "https:/")):
            os.environ.pop(key, None)


_strip_problematic_cgi_env_vars()


def _env_bool(key, default=False):
    value = os.getenv(key)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(key, default):
    value = os.getenv(key)
    if value is None:
        return default
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _env_list(key, default=None):
    value = os.getenv(key)
    if value is None:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def _env_str(key, default=""):
    value = os.getenv(key)
    if value is None:
        return default
    value = value.strip()
    if len(value) >= 2 and (
        (value[0] == '"' and value[-1] == '"')
        or (value[0] == "'" and value[-1] == "'")
    ):
        value = value[1:-1].strip()
    return value


def _env_first(keys, default=""):
    for key in keys:
        value = _env_str(key, "")
        if value:
            return value
    return default


def _env_smtp_password(key, default=""):
    """
    Normalize SMTP app passwords.

    Many providers display app passwords grouped by spaces (for readability),
    while SMTP auth expects the compact token.
    """
    raw_value = _env_str(key, default)
    return "".join(raw_value.split())


def _is_placeholder_secret(value):
    normalized = (value or "").strip().lower()
    if normalized in {
        "",
        "replace-with-fast2sms-api-key",
        "replace-with-api-key",
        "your-fast2sms-api-key",
        "your_fast2sms_api_key",
        "your-real-fast2sms-key",
        "your_real_fast2sms_key",
        "changeme",
    }:
        return True
    if normalized.startswith("replace-with-"):
        return True
    if normalized.startswith("your_") and normalized.endswith("_key"):
        return True
    if normalized.startswith("your-") and normalized.endswith("-key"):
        return True
    return False


def _git_head_version():
    git_dir = BASE_DIR / ".git"
    head_path = git_dir / "HEAD"
    if not head_path.exists():
        return ""
    try:
        head_ref = head_path.read_text(encoding="utf-8").strip()
    except OSError:
        return ""
    if not head_ref:
        return ""
    if head_ref.startswith("ref:"):
        ref_path = git_dir / head_ref.split(" ", 1)[1].strip()
        if not ref_path.exists():
            return ""
        try:
            return ref_path.read_text(encoding="utf-8").strip()[:12]
        except OSError:
            return ""
    return head_ref[:12]


def _resolve_static_asset_version():
    configured = _env_str("STATIC_ASSET_VERSION", "")
    if configured:
        return configured

    commit_env_keys = [
        "SOURCE_VERSION",
        "RAILWAY_GIT_COMMIT_SHA",
        "RENDER_GIT_COMMIT",
        "VERCEL_GIT_COMMIT_SHA",
    ]
    for key in commit_env_keys:
        value = _env_str(key, "")
        if value:
            return value[:12]

    git_version = _git_head_version()
    if git_version:
        return git_version

    static_dir = BASE_DIR / "static"
    try:
        return str(int(static_dir.stat().st_mtime))
    except OSError:
        return "1"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _env_str(
    "DJANGO_SECRET_KEY",
    _env_str("SECRET_KEY", "django-insecure-*=&sde3n-m0o*h6(jntu+-k%8lmc@@2x&!voya)_8t+1!$3!!j"),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", ["localhost", "127.0.0.1"])
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS", [])

USE_X_FORWARDED_HOST = _env_bool("DJANGO_USE_X_FORWARDED_HOST", default=True)
if _env_bool("DJANGO_TRUST_X_FORWARDED_PROTO", default=True):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
FORCE_SCRIPT_NAME = _env_str("DJANGO_FORCE_SCRIPT_NAME", "")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard.apps.DashboardConfig',
    'corsheaders'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'dashboard.middleware.MySQLConnectionRecoveryMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobexhibition.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'dashboard.context_processors.admin_profile_context',
                'dashboard.context_processors.candidate_panel_context',
                'dashboard.context_processors.panel_notifications_context',
                'dashboard.context_processors.static_assets_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobexhibition.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = _env_str("DB_ENGINE", "django.db.backends.mysql")
PAYMENT_DB_ALIAS = _env_str("PAYMENT_DB_ALIAS", "payment")
PAYMENT_DB_ENABLED = _env_bool("PAYMENT_DB_ENABLED", default=True)

if DB_ENGINE in {"sqlite", "django.db.backends.sqlite3"}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _env_str("DB_SQLITE_PATH", str(BASE_DIR / 'db.sqlite3')),
        }
    }
else:
    db_options = {
        'charset': 'utf8mb4',
        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        'connect_timeout': _env_int("DB_CONNECT_TIMEOUT", 20),
    }
    db_read_timeout = _env_int("DB_READ_TIMEOUT", 30)
    if db_read_timeout > 0:
        db_options['read_timeout'] = db_read_timeout
    db_write_timeout = _env_int("DB_WRITE_TIMEOUT", 30)
    if db_write_timeout > 0:
        db_options['write_timeout'] = db_write_timeout
    db_ssl_ca = _env_str("DB_SSL_CA", "")
    if db_ssl_ca:
        db_options['ssl'] = {'ca': db_ssl_ca}

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': _env_str("DB_NAME", "u529002218_jobdekhao123"),
            'USER': _env_str("DB_USER", "u529002218_jobdekhao123"),
            'PASSWORD': _env_str("DB_PASSWORD", "Jobdekhao123"),
            'HOST': _env_str("DB_HOST", "srv685.hstgr.io"),
            'PORT': _env_str("DB_PORT", "3306"),
            'CONN_MAX_AGE': _env_int("DB_CONN_MAX_AGE", 60),
            'CONN_HEALTH_CHECKS': _env_bool("DB_CONN_HEALTH_CHECKS", default=True),
            'OPTIONS': db_options,
        }
    }

if PAYMENT_DB_ENABLED and PAYMENT_DB_ALIAS and PAYMENT_DB_ALIAS != "default":
    payment_db_engine = _env_str("PAYMENT_DB_ENGINE", "django.db.backends.mysql")
    if payment_db_engine in {"sqlite", "django.db.backends.sqlite3"}:
        DATABASES[PAYMENT_DB_ALIAS] = {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _env_str(
                "PAYMENT_DB_SQLITE_PATH",
                _env_str("DB_SQLITE_PATH", str(BASE_DIR / 'payment.sqlite3')),
            ),
        }
    else:
        payment_db_options = {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': _env_int(
                "PAYMENT_DB_CONNECT_TIMEOUT",
                _env_int("DB_CONNECT_TIMEOUT", 20),
            ),
        }
        payment_db_read_timeout = _env_int(
            "PAYMENT_DB_READ_TIMEOUT",
            _env_int("DB_READ_TIMEOUT", 30),
        )
        if payment_db_read_timeout > 0:
            payment_db_options['read_timeout'] = payment_db_read_timeout
        payment_db_write_timeout = _env_int(
            "PAYMENT_DB_WRITE_TIMEOUT",
            _env_int("DB_WRITE_TIMEOUT", 30),
        )
        if payment_db_write_timeout > 0:
            payment_db_options['write_timeout'] = payment_db_write_timeout
        payment_db_ssl_ca = _env_str("PAYMENT_DB_SSL_CA", _env_str("DB_SSL_CA", ""))
        if payment_db_ssl_ca:
            payment_db_options['ssl'] = {'ca': payment_db_ssl_ca}

        DATABASES[PAYMENT_DB_ALIAS] = {
            'ENGINE': payment_db_engine,
            'NAME': _env_str(
                "PAYMENT_DB_NAME",
                _env_str("DB_NAME", "u529002218_jobdekhao123"),
            ),
            'USER': _env_str(
                "PAYMENT_DB_USER",
                _env_str("DB_USER", "u529002218_jobdekhao123"),
            ),
            'PASSWORD': _env_str(
                "PAYMENT_DB_PASSWORD",
                _env_str("DB_PASSWORD", "Jobdekhao123"),
            ),
            'HOST': _env_str("PAYMENT_DB_HOST", _env_str("DB_HOST", "srv685.hstgr.io")),
            'PORT': _env_str("PAYMENT_DB_PORT", _env_str("DB_PORT", "3306")),
            'CONN_MAX_AGE': _env_int(
                "PAYMENT_DB_CONN_MAX_AGE",
                _env_int("DB_CONN_MAX_AGE", 60),
            ),
            'CONN_HEALTH_CHECKS': _env_bool(
                "PAYMENT_DB_CONN_HEALTH_CHECKS",
                default=_env_bool("DB_CONN_HEALTH_CHECKS", default=True),
            ),
            'OPTIONS': payment_db_options,
        }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ASSET_VERSION = _resolve_static_asset_version()
if not DEBUG:
    STATICFILES_STORAGE = _env_str(
        "DJANGO_STATICFILES_STORAGE",
        "whitenoise.storage.CompressedManifestStaticFilesStorage",
    )

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
SERVE_MEDIA_FILES = _env_bool("SERVE_MEDIA_FILES", default=True)

# Email (SMTP) configuration
EMAIL_BACKEND = _env_str("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = _env_str("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = _env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = _env_str("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = _env_smtp_password("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", default=False)
DEFAULT_FROM_EMAIL = _env_str(
    "DEFAULT_FROM_EMAIL",
    "JobExhibition <no-reply@jobexhibition.com>",
)
SITE_TITLE = _env_str("SITE_TITLE", "JobExhibition")

# Optional fallback SMTP sender (used when primary SMTP fails).
EMAIL_FALLBACK_HOST = _env_str("EMAIL_FALLBACK_HOST", EMAIL_HOST)
EMAIL_FALLBACK_PORT = _env_int("EMAIL_FALLBACK_PORT", EMAIL_PORT)
EMAIL_FALLBACK_HOST_USER = _env_str("EMAIL_FALLBACK_HOST_USER", "")
EMAIL_FALLBACK_HOST_PASSWORD = _env_smtp_password("EMAIL_FALLBACK_HOST_PASSWORD", "")
EMAIL_FALLBACK_USE_TLS = _env_bool("EMAIL_FALLBACK_USE_TLS", default=EMAIL_USE_TLS)
EMAIL_FALLBACK_USE_SSL = _env_bool("EMAIL_FALLBACK_USE_SSL", default=EMAIL_USE_SSL)
EMAIL_FALLBACK_FROM_EMAIL = _env_str("EMAIL_FALLBACK_FROM_EMAIL", "")

AUTO_APPROVE_HOURS = _env_int("AUTO_APPROVE_HOURS", 24)

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/admin-dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# Production hardening toggles for VPS deployments (safe defaults).
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_HSTS_SECONDS = _env_int("DJANGO_SECURE_HSTS_SECONDS", 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)

# OTP / SMS settings
_otp_sms_api_key = _env_first(
    [
        "OTP_SMS_API_KEY",
        "OTP_FAST2SMS_API_KEY",
        "FAST2SMS_API_KEY",
    ],
    "",
)
OTP_SMS_API_KEY = "XW8UdfD7hV5soeyuQG9ONj0kpmFBlJS2w6nLirME1zaCKZ3TvHyYXTkDj31MEqIiUfwQm4V8pKCcH6av" if _is_placeholder_secret(_otp_sms_api_key) else _otp_sms_api_key
_otp_default_provider = 'fast2sms'
OTP_SMS_PROVIDER = _env_str('OTP_SMS_PROVIDER', _otp_default_provider).lower()
OTP_SMS_API_URL = _env_str('OTP_SMS_API_URL', 'https://www.fast2sms.com/dev/bulkV2')
OTP_SMS_MESSAGE_TEMPLATE = _env_str(
    'OTP_SMS_MESSAGE_TEMPLATE',
    'Your OTP for JobExhibition is {otp}. It is valid for {ttl_minutes} minutes.',
)
OTP_SMS_TIMEOUT_SECONDS = _env_int('OTP_SMS_TIMEOUT_SECONDS', 10)
OTP_FAST2SMS_ROUTE = _env_str('OTP_FAST2SMS_ROUTE', 'dlt')
OTP_FAST2SMS_LANGUAGE = _env_str('OTP_FAST2SMS_LANGUAGE', 'english')
OTP_FAST2SMS_FLASH = _env_int('OTP_FAST2SMS_FLASH', 0)
OTP_FAST2SMS_SENDER_ID = _env_str('OTP_FAST2SMS_SENDER_ID', 'GBJOB')
OTP_FAST2SMS_ENTITY_ID = _env_str('OTP_FAST2SMS_ENTITY_ID', '')
OTP_FAST2SMS_TEMPLATE_ID = _env_str('OTP_FAST2SMS_TEMPLATE_ID', '')
OTP_FAST2SMS_MESSAGE_ID = _env_str('OTP_FAST2SMS_MESSAGE_ID', '211271')
OTP_FAST2SMS_VARIABLES_VALUES = _env_str('OTP_FAST2SMS_VARIABLES_VALUES', '{otp}|{ttl_minutes}|')
OTP_FAST2SMS_REGISTER_MESSAGE_ID = _env_str('OTP_FAST2SMS_REGISTER_MESSAGE_ID', '211271')
OTP_FAST2SMS_FORGOT_PASSWORD_MESSAGE_ID = _env_str('OTP_FAST2SMS_FORGOT_PASSWORD_MESSAGE_ID', '211269')
OTP_FAST2SMS_ACCOUNT_DELETE_MESSAGE_ID = _env_str('OTP_FAST2SMS_ACCOUNT_DELETE_MESSAGE_ID', '211270')
OTP_FAST2SMS_LOGIN_MESSAGE_ID = _env_str('OTP_FAST2SMS_LOGIN_MESSAGE_ID', '211272')
OTP_FAST2SMS_REGISTER_VARIABLES_VALUES = _env_str('OTP_FAST2SMS_REGISTER_VARIABLES_VALUES', '{otp}|{ttl_minutes}|')
OTP_FAST2SMS_FORGOT_PASSWORD_VARIABLES_VALUES = _env_str('OTP_FAST2SMS_FORGOT_PASSWORD_VARIABLES_VALUES', '{otp}|{ttl_minutes}|')
OTP_FAST2SMS_ACCOUNT_DELETE_VARIABLES_VALUES = _env_str('OTP_FAST2SMS_ACCOUNT_DELETE_VARIABLES_VALUES', '{otp}|{ttl_minutes}|')
OTP_FAST2SMS_LOGIN_VARIABLES_VALUES = _env_str('OTP_FAST2SMS_LOGIN_VARIABLES_VALUES', '{otp}|{ttl_minutes}|')
OTP_FAST2SMS_SCHEDULE_TIME = _env_str('OTP_FAST2SMS_SCHEDULE_TIME', '')
OTP_DEBUG_SHOW_IN_MESSAGES = _env_bool('OTP_DEBUG_SHOW_IN_MESSAGES', default=False)
OTP_ALLOW_DEBUG_FALLBACK = _env_bool('OTP_ALLOW_DEBUG_FALLBACK', default=False)
OTP_ALLOW_CONSOLE_EMAIL = _env_bool('OTP_ALLOW_CONSOLE_EMAIL', default=False)
LOGIN_OTP_REQUIRED = _env_bool('LOGIN_OTP_REQUIRED', default=False)
FORGOT_PASSWORD_OTP_REQUIRED = _env_bool('FORGOT_PASSWORD_OTP_REQUIRED', default=True)

# Subscription / Payment gateway settings
PAYMENT_SERVICE_PORT = _env_int("PORT", 3000)
PAYMENT_SERVICE_NODE_ENV = _env_str("NODE_ENV", "development")
PAYMENT_GATEWAY_PROVIDER = _env_str("PAYMENT_GATEWAY_PROVIDER", "PhonePe")
PAYMENT_GATEWAY_INITIATE_URL = _env_str(
    "PAYMENT_GATEWAY_INITIATE_URL",
    "",
)
PAYMENT_GATEWAY_STATUS_URL = _env_str(
    "PAYMENT_GATEWAY_STATUS_URL",
    "",
)
PAYMENT_GATEWAY_CALLBACK_SECRET = _env_str("PAYMENT_GATEWAY_CALLBACK_SECRET", "")
PAYMENT_GATEWAY_TIMEOUT_SECONDS = _env_int("PAYMENT_GATEWAY_TIMEOUT_SECONDS", 20)
PAYMENT_GATEWAY_DEMO_AUTO_SUCCESS = _env_bool(
    "PAYMENT_GATEWAY_DEMO_AUTO_SUCCESS",
    default=False,
)
PAYMENT_GATEWAY_INTERNAL_FALLBACK = _env_bool(
    "PAYMENT_GATEWAY_INTERNAL_FALLBACK",
    default=True,
)
PAYMENT_PUBLIC_BASE_URL = _env_first(
    [
        "PAYMENT_PUBLIC_BASE_URL",
        "PUBLIC_BASE_URL",
        "APP_BASE_URL",
        "SITE_BASE_URL",
    ],
    "",
)
PAYMENT_FORCE_HTTPS_URLS = _env_bool("PAYMENT_FORCE_HTTPS_URLS", default=not DEBUG)
PAYMENT_ALLOWED_HOSTS = _env_list("PAYMENT_ALLOWED_HOSTS", [])

# PhonePe compatibility keys (direct integration defaults to latest v2 endpoints)
PHONEPE_BASE_URL = _env_str("PHONEPE_BASE_URL", "https://api.phonepe.com/apis")
PHONEPE_OAUTH_BASE_URL = _env_str("PHONEPE_OAUTH_BASE_URL", "https://api.phonepe.com/apis/identity-manager")
PHONEPE_PAY_PATH = _env_str("PHONEPE_PAY_PATH", "/checkout/v2/pay")
PHONEPE_STATUS_PATH = _env_str(
    "PHONEPE_STATUS_PATH",
    "/checkout/v2/order/{merchant_transaction_id}/status",
)
PHONEPE_CLIENT_ID = _env_first(["PHONEPE_CLIENT_ID", "MERCHANT_ID"], "SU2508261540303520112151")
PHONEPE_CLIENT_SECRET = _env_first(["PHONEPE_CLIENT_SECRET", "SALT_KEY"], "75dbd341-4f7f-4120-a056-856f295a3ecb")
PHONEPE_MERCHANT_ID = _env_first(["MERCHANT_ID", "PHONEPE_CLIENT_ID"], PHONEPE_CLIENT_ID)
PHONEPE_SALT_KEY = _env_first(["SALT_KEY", "PHONEPE_CLIENT_SECRET"], PHONEPE_CLIENT_SECRET)
PHONEPE_SALT_INDEX = _env_int("SALT_INDEX", _env_int("PHONEPE_SALT_INDEX", 1))
PHONEPE_CLIENT_VERSION = _env_str("PHONEPE_CLIENT_VERSION", "1")
PHONEPE_ENV = _env_str("PHONEPE_ENV", "UAT")
MERCHANT_REDIRECT_URL = _env_str("MERCHANT_REDIRECT_URL", "/payment/redirect/")
MERCHANT_CALLBACK_URL = _env_str("MERCHANT_CALLBACK_URL", "/api/payment/callback/")
MERCHANT_USERNAME = _env_str("MERCHANT_USERNAME", "")
MERCHANT_PASSWORD = _env_str("MERCHANT_PASSWORD", "")
PAYMENT_QR_UPI_ID = _env_str("PAYMENT_QR_UPI_ID", _env_str("MERCHANT_USERNAME", ""))
PAYMENT_QR_PAYEE_NAME = _env_str("PAYMENT_QR_PAYEE_NAME", "Job Exhibition")
PAYMENT_QR_NOTE_PREFIX = _env_str("PAYMENT_QR_NOTE_PREFIX", "Subscription")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://jobdekho.jobexhibition.com",
]

CORS_ALLOW_ALL_ORIGINS = True
